import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = join(import.meta.dirname, '..')
const html = readFileSync(join(root, 'assets', 'pet.html'), 'utf8')
const css = readFileSync(join(root, 'assets', 'pet.css'), 'utf8')
const petPreload = readFileSync(join(root, 'src', 'pet-preload.ts'), 'utf8')
const petCharacter = readFileSync(join(root, 'src', 'pet-character.ts'), 'utf8')
const petSkin = readFileSync(join(root, 'src', 'pet-skin.ts'), 'utf8')
const sharedPreload = readFileSync(join(root, 'src', 'preload.ts'), 'utf8')
const main = readFileSync(join(root, 'src', 'main.ts'), 'utf8')
const petWindow = readFileSync(join(root, 'src', 'pet-window.ts'), 'utf8')
const tsdown = readFileSync(join(root, 'tsdown.config.ts'), 'utf8')
const packageJson = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as { build: { files: string[] } }

describe('desktop pet renderer contract', () => {
  it('ships a script-free fixed local page with stable controls', () => {
    for (const id of [
      'pet-page', 'bubble', 'session-label', 'hide-pet', 'status-text', 'reply-text',
      'approval', 'approval-tool', 'approval-reason', 'approval-count',
      'reject-approval', 'allow-approval', 'open-main', 'mascot', 'pet-character', 'pet-skin', 'state-indicator',
    ]) expect(html).toContain('id="' + id + '"')
    expect(html).toContain("script-src 'none'")
    expect(html).toContain("connect-src 'none'")
    expect(html).toContain("img-src 'self' data:")
    expect(html).toContain('<canvas id="pet-character" width="192" height="192"')
    expect(html).toContain('aria-live="polite"')
    expect(html).not.toMatch(/<script|\son[a-z]+=/iu)
  })

  it('keeps layout stable and honors accessibility preferences', () => {
    expect(css).toContain('width: 240px')
    expect(css).toContain('max-height: 204px')
    expect(css).toContain('right: -7px')
    expect(css).toContain('width: 96px')
    expect(css).toContain('.mascot canvas { image-rendering: pixelated; }')
    expect(css).toContain('[data-custom-skin="true"][data-state="idle"]')
    expect(css).toContain('.mascot canvas {\n    border: 2px solid CanvasText;')
    expect(css).toContain('filter: grayscale(1) contrast(2)')
    expect(css).toContain('object-fit: contain')
    expect(css).toContain('touch-action: none')
    expect(css).toContain('-webkit-app-region: no-drag')
    expect(css).not.toContain('-webkit-app-region: drag')
    expect(css).toContain('[hidden] { display: none !important; }')
    expect(css).toContain('border-radius: 8px')
    expect(css).toContain('[data-state="idle"] .mascot')
    expect(css).toContain('[data-state="success"] .mascot')
    expect(css).toContain('[data-state="error"] .mascot')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(css).toContain('@media (forced-colors: active)')
    expect(css).toContain(':focus-visible')
    expect(css).not.toContain('linear-gradient')
  })

  it('drives an original desktop-only character through every DSH state', () => {
    for (const mode of ['idle', 'thinking', 'speaking', 'approval', 'success', 'error', 'unavailable', 'dragging']) {
      expect(petCharacter).toContain(mode + ':')
    }
    expect(petCharacter).toContain('requestFrame(callback: FrameRequestCallback)')
    expect(petCharacter).toContain('PET_CHARACTER_SPRITES')
    expect(petCharacter).toContain("source: 'pet-character/runtime/idle.png'")
    expect(petCharacter).toContain('image.naturalWidth === spec.frameCount * 192')
    expect(petCharacter).toContain('drawPetCharacterSprite')
    expect(petCharacter).toContain('drawPetCharacter(this.canvas, pose)')
    expect(petCharacter).toContain('animator.loadSprites(() => new Image())')
    expect(petCharacter).toContain('if (!this.active || this.reducedMotion')
    expect(petCharacter).toContain("if (mode === 'success' || mode === 'error')")
    expect(petCharacter).toContain('if (frameKey === this.lastFrameKey) return')
    expect(petCharacter).toContain('context.translate(x, y)')
    expect(petPreload).toContain('createPetCharacter')
    expect(petPreload).toContain('character?.setMode(latest.mode)')
    expect(petPreload).toContain('character?.setDragging(true)')
    expect(petPreload).toContain('character?.setDragging(false)')
    expect(petPreload).toContain("document.addEventListener('visibilitychange', applySkin)")
    expect(petPreload).toContain('character?.setActive(builtIn')
    expect(petPreload).toContain("ipcRenderer.on('pet:visibility'")
    expect(petPreload).toContain("skinImage.addEventListener('error'")
    expect(petSkin).toContain("kind: 'builtin' | 'custom'")
    expect(petSkin).toContain("skin.kind === 'builtin'")
    expect(petPreload).toContain('selectPetSkinUrl(latestSkin, reducedMotion.matches, visible)')
    expect(css).toContain('[data-custom-skin="false"] .state-indicator {\n    display: block;')
    expect(petPreload).not.toContain('fetch(')
    expect(petCharacter).not.toContain('http://')
    expect(petCharacter).not.toContain('https://')
    expect(packageJson.build.files).toContain('assets/pet-character/runtime/*.png')
    expect(packageJson.build.files).not.toContain('assets/pet-character/source/*.png')
  })

  it('renders bounded text through a dedicated narrow preload', () => {
    expect(tsdown).toContain("entry: ['src/preload.ts', 'src/pet-preload.ts']")
    expect(petPreload).toContain("ipcRenderer.on('pet:state'")
    expect(petPreload).toContain("ipcRenderer.invoke('pet:respond', pending.id, outcome)")
    expect(petPreload).toContain("ipcRenderer.send('pet:focus-main')")
    expect(petPreload).toContain("ipcRenderer.send('pet:hide')")
    expect(petPreload).toContain("ipcRenderer.send('pet:interaction', interactive)")
    expect(petPreload).toContain('document.elementFromPoint(clientX, clientY)')
    expect(petPreload).toContain("ipcRenderer.send('pet:set-shape'")
    expect(petPreload).toContain('bubble.getBoundingClientRect()')
    expect(petPreload).toContain("ipcRenderer.send('pet:drag-start'")
    expect(petPreload).toContain("ipcRenderer.send('pet:drag-move'")
    expect(petPreload).toContain("ipcRenderer.send('pet:drag-end')")
    expect(petPreload).toContain("mascot.addEventListener('pointercancel', event => { finishDrag(event, false) })")
    expect(petPreload).toContain("mascot.addEventListener('lostpointercapture'")
    expect(petPreload).toContain("window.addEventListener('blur', cancelActiveDrag)")
    expect(petPreload).toContain("window.addEventListener('pagehide', () => { cancelActiveDrag(); character?.dispose() })")
    expect(petPreload).toContain('if (open && !finished.moved)')
    expect(petPreload).toContain("ipcRenderer.send('pet:ready')")
    expect(petPreload).toContain('Array.from(value.replace')
    expect(petPreload).not.toMatch(/innerHTML|outerHTML|insertAdjacentHTML|document\.write|eval\(|new Function/u)
    expect(petPreload).not.toContain('contextBridge')
  })

  it('accepts foreground session signals only through same-window messages', () => {
    expect(sharedPreload).toContain("const PET_ACTIVE_SESSION_MESSAGE = 'dsh/desktop-pet-active-session'")
    expect(sharedPreload).toContain('event.source !== window || event.origin !== window.location.origin')
    expect(sharedPreload).toContain("ipcRenderer.send('pet:set-active-session', sessionId)")
    expect(main).toContain("state.thinking === true) return { mode: 'thinking'")
    expect(main).toContain('event.sender !== mainWindow.webContents')
    expect(main).toContain('new URL(event.sender.getURL()).origin === trustedOrigin')
  })

  it('shows the pet only while the main window is hidden and keeps manual hiding', () => {
    expect(main).toContain("mainWindow.on('show', () => { petWindow?.setMainVisible(true) })")
    expect(main).toContain("mainWindow.on('hide', () => { petWindow?.setMainVisible(false) })")
    expect(main).toContain('if (!quitting) petWindow?.setMainVisible(false)')
    expect(main).toContain('mainWindow?.hide()')
    expect(main).toContain("label: '桌面宠物', type: 'checkbox'")
    expect(main).toContain("label: '启用桌面宠物'")
    expect(petWindow).toContain('if (!this.mainVisible && !this.settings.manuallyHidden) {')
    expect(petWindow).toContain('window.showInactive()')
    expect(petWindow).toContain('window.setShape')
    expect(petWindow).toContain('window.setIgnoreMouseEvents(false)')
    expect(petWindow).toContain('const STREAM_UPDATE_MS = 100')
    expect(petWindow).toContain("state.mode === 'speaking'")
    expect(petWindow).toContain("join(options.userData, 'desktop-pet.json')")
    expect(petWindow).not.toContain('DSH_HOME')
  })

  it('configures bounded static and animated skins from the File menu', () => {
    expect(main).toContain("label: '个性化皮肤'")
    expect(main).toContain("label: '选择静态图片或动态 GIF...'")
    expect(main).toContain("extensions: ['png', 'jpg', 'jpeg', 'webp', 'gif']")
    expect(main).toContain("label: '恢复默认皮肤'")
    expect(petWindow).toContain("join(options.userData, 'desktop-pet-skin.png')")
    expect(petWindow).toContain("join(options.userData, 'desktop-pet-skin.gif')")
    expect(petWindow).toContain('const MAX_SKIN_SOURCE_BYTES = 8 * 1024 * 1024')
    expect(petWindow).toContain('const MAX_ANIMATED_SKIN_BYTES = 2 * 1024 * 1024')
    expect(petWindow).toContain('const MAX_ANIMATED_SKIN_FRAMES = 120')
    expect(petWindow).toContain('countGifFramesBounded(bytes)')
    expect(petWindow.indexOf('countGifFramesBounded(bytes)')).toBeLessThan(petWindow.indexOf('new GifReader(bytes)'))
    expect(petWindow).toContain('new GifReader(bytes)')
    expect(petWindow).toContain('nativeImage.createFromBitmap(firstFrame')
    expect(petWindow).toContain("this.window.webContents.send('pet:skin'")
    expect(petWindow).toContain("this.window.webContents.send('pet:visibility', visible)")
    expect(petPreload).toContain("ipcRenderer.on('pet:skin'")
    expect(petSkin).toContain("const GIF_PREFIX = 'data:image/gif;base64,'")
    expect(petPreload).toContain("window.matchMedia('(prefers-reduced-motion: reduce)')")
    expect(petPreload).toContain('selectPetSkinUrl(latestSkin, reducedMotion.matches, visible)')
    expect(petSkin).toContain('MAX_SKIN_DATA_URL_LENGTH')
    expect(petPreload).not.toContain('sourcePath')
  })

  it('keeps pet IPC scoped to its exact window and opaque approval identifier', () => {
    expect(main).toContain('window?.matchesSender(event.sender, petPage)')
    expect(main).toContain("ipcMain.handle('pet:respond'")
    expect(main).toContain('events.decide({ approvalId, outcome })')
    expect(main).not.toContain('events.decide({ approvalId, outcome, rpcId')
    expect(main).toContain("ipcMain.on('pet:hide'")
    expect(main).toContain("ipcMain.on('pet:set-shape'")
    expect(petWindow).toContain('input.x + input.width > WIDTH')
    expect(main).toContain('parsePetWindowShape(value)')
    expect(main).toContain("ipcMain.on('pet:drag-start'")
    expect(main).toContain("ipcMain.on('pet:drag-move'")
    expect(main).toContain("ipcMain.on('pet:drag-end'")
    expect(main).toContain('Math.abs(input.x) > 1_000_000')
    expect(main).toContain('await stopPet()')
  })
})
